<%@page import="com.xiaoshudian.util.StringUtils"%>
<%@page import="java.util.List"%>
<%@page import="com.xiaoshudian.data.domain.ITArticle"%>
<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta name="Keywords" content="小数点 IT资讯 科技 新闻 博客 小数点科技频道"/>
<meta name="Description" content="小数点 IT资讯 科技 新闻 博客 小数点科技频道"/>
<title>小数点 IT资讯 科技 新闻 博客 小数点科技频道</title>
<%
	long start2 = System.currentTimeMillis();
	String strP = request.getParameter("p");
	int p = StringUtils.String2Int(strP, 1);
	long start = StringUtils.String2Long(String.valueOf(request.getAttribute("start")),System.currentTimeMillis());
	ITArticle article = new ITArticle();
	long articleCount = article.totalCount();
	int maxPage = (int)((articleCount % 20 == 0) ? (articleCount / 20) : (articleCount / 20 + 1));
	p = ( p < 1 ) ? 1 : p;
	p = ( p > maxPage ) ? maxPage : p;
	List<ITArticle> articles = (List<ITArticle>)article.specifyByPage("id"," where flag = 0 order by posttime desc ",p, 20);
	if( articles == null || articles.isEmpty() ){
		response.sendRedirect("it.jsp");
	}
%>
</head>
<body>
	
	<jsp:include page="top.jsp">
		<jsp:param value="<%=articleCount %>" name="totalCount"/>
	</jsp:include>
	<div id="content">
		
		<div id="left">
			<div class="toolbar">
				<div class="left">IT资讯</div>
				<div class="right">列表模式:标题+摘要 | 标题+全文 | 仅标题</div>
				<div class="clear"></div>
			</div>
			<ul>
				<%for( ITArticle a : articles ){
					ITArticle thisArticle = a.getById(a.getId());
				%>
				<li class="blog">
					<div class="blog_title">
						<h2><image src="../images/b1.gif" class="mr10"/><a href="itdetail.jsp?id=<%=thisArticle.getId()%>"><%=thisArticle.getTitle() %></a></h2>
						<div class="outline">
							<span class="tag">分类:&nbsp;<%=thisArticle.getTag() %></span>
						</div>
					</div>
					<span class="blg_date"></span>
					<div class="blog_content">
						<%=thisArticle.getContent() %>
					</div>
					<div class="blog_bottom">
						发布于 1小时前   阅读(35)|评论(24)|投票(0)|收藏(3)  阅读全文
					</div>
				</li>
				<%}%>
			</ul>
		</div>
		<jsp:include page="right.jsp">
			<jsp:param value="<%=articleCount%>" name="totalCount"/>
		</jsp:include>
		<div class="clear"></div>
	</div>
	
	<jsp:include page="page.jsp">
		<jsp:param value="1" name="minPage"/>
		<jsp:param value="<%=maxPage %>" name="maxPage"/>
		<jsp:param value="it.jsp" name="url"/>
		<jsp:param value="<%=p %>" name="curPage"/>
	</jsp:include>
	
	<jsp:include page="bottom.jsp"/>
	
</body>
</html>
<!-- Generated by xiaoshudian [all:<%=System.currentTimeMillis() - start%>ms,process:<%=System.currentTimeMillis()-start2%>ms -->