<%@page import="com.xiaoshudian.data.domain.ITArticle"%>
<%@page import="com.xiaoshudian.util.StringUtils"%>
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>小数点 IT资讯 科技 新闻 博客 小数点科技频道</title>
</head>
<%
	long start2 = System.currentTimeMillis();
	String newsId = request.getParameter("id");
	int id = StringUtils.String2Int(newsId);
	long start = StringUtils.String2Long(String.valueOf(request.getAttribute("start")),System.currentTimeMillis());
	if( StringUtils.isBlank(newsId) ){
		response.sendRedirect("it.jsp");
	}
	ITArticle article = new ITArticle();
	article = article.getById(id);
	
	long articleCount = article.totalCount();
%>	
<body>

	<jsp:include page="top.jsp">
		<jsp:param value="<%=articleCount %>" name="totalCount"/>
	</jsp:include>
	
	<div id="content">
		<div id="left">
			<ul>
			<li class="blog">
					<div class="blog_title">
						<h2><image src="../images/b1.gif" class="mr10"/><%=article.getTitle() %></h2>
						<div class="outline">
							<span class="tag">分类:<%=article.getTag() %></span>
						</div>
					</div>
					<span class="blg_date"></span>
					<div class="blog_content">
						<%=article.getContent() %>
					</div>
					<div class="blog_bottom">
						发布于 1小时前   阅读(35)|评论(24)|投票(0)|收藏(3)  阅读全文
					</div>
				</li>	
			</ul>	
		</div>
		<jsp:include page="right.jsp"/>
		<div class="clear"></div>
	</div>
	
	<jsp:include page="bottom.jsp"/>
	
</body>
</html>
<!-- Generated by xiaoshudian [all:<%=System.currentTimeMillis() - start%>ms,process:<%=System.currentTimeMillis()-start2%>ms -->